save_dir: ./saved_models
save_name: busDataset_40
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 131072
num_eval_iter: 100
num_labels: 40
batch_size: 16
eval_batch_size: 8
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: AdamW
lr: 0.003
momentum: 0.9
weight_decay: 0.0005
amp: False
net: resnet34
net_from_name: True
depth: 0
widen_factor: 0
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: busDataset
train_sampler: RandomSampler
num_classes: 2
num_workers: 0
alg: flexmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: 0
